name: Build MonoPingPong

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Test project
      run: dotnet test --no-build --configuration Release --verbosity normal
      continue-on-error: true  # Continue even if no tests exist

    - name: Code formatting check
      run: dotnet format MonoPingPong.sln --verify-no-changes --verbosity diagnostic
      continue-on-error: true  # Don't fail build on formatting issues

    - name: Publish artifacts
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MonoPingPong-Release
        path: ./publish/
        retention-days: 30

  release:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish release
      run: dotnet publish --configuration Release --output ./release

    - name: Create release archive
      run: Compress-Archive -Path ./release/* -DestinationPath MonoPingPong-${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: MonoPingPong-${{ github.ref_name }}.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
